/**
 * currencies.js - Liste complète des devises mondiales
 */

export const CURRENCIES = [
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'USD', symbol: '$', name: 'Dollar américain' },
  { code: 'GBP', symbol: '£', name: 'Livre sterling' },
  { code: 'JPY', symbol: '¥', name: 'Yen japonais' },
  { code: 'CHF', symbol: 'CHF', name: 'Franc suisse' },
  { code: 'CAD', symbol: 'C$', name: 'Dollar canadien' },
  { code: 'AUD', symbol: 'A$', name: 'Dollar australien' },
  { code: 'CNY', symbol: '¥', name: 'Yuan chinois' },
  { code: 'INR', symbol: '₹', name: 'Roupie indienne' },
  { code: 'BRL', symbol: 'R$', name: 'Réal brésilien' },
  { code: 'ZAR', symbol: 'R', name: 'Rand sud-africain' },
  { code: 'RUB', symbol: '₽', name: 'Rouble russe' },
  { code: 'KRW', symbol: '₩', name: 'Won sud-coréen' },
  { code: 'MXN', symbol: 'Mex$', name: 'Peso mexicain' },
  { code: 'SGD', symbol: 'S$', name: 'Dollar de Singapour' },
  { code: 'HKD', symbol: 'HK$', name: 'Dollar de Hong Kong' },
  { code: 'NOK', symbol: 'kr', name: 'Couronne norvégienne' },
  { code: 'SEK', symbol: 'kr', name: 'Couronne suédoise' },
  { code: 'DKK', symbol: 'kr', name: 'Couronne danoise' },
  { code: 'PLN', symbol: 'zł', name: 'Zloty polonais' },
  { code: 'THB', symbol: '฿', name: 'Baht thaïlandais' },
  { code: 'IDR', symbol: 'Rp', name: 'Roupie indonésienne' },
  { code: 'MYR', symbol: 'RM', name: 'Ringgit malaisien' },
  { code: 'PHP', symbol: '₱', name: 'Peso philippin' },
  { code: 'CZK', symbol: 'Kč', name: 'Couronne tchèque' },
  { code: 'HUF', symbol: 'Ft', name: 'Forint hongrois' },
  { code: 'ILS', symbol: '₪', name: 'Shekel israélien' },
  { code: 'CLP', symbol: 'CLP$', name: 'Peso chilien' },
  { code: 'NZD', symbol: 'NZ$', name: 'Dollar néo-zélandais' },
  { code: 'AED', symbol: 'د.إ', name: 'Dirham des EAU' },
  { code: 'SAR', symbol: 'ر.س', name: 'Riyal saoudien' },
  { code: 'TRY', symbol: '₺', name: 'Livre turque' },
  { code: 'ARS', symbol: 'AR$', name: 'Peso argentin' },
  { code: 'COP', symbol: 'COL$', name: 'Peso colombien' },
  { code: 'PEN', symbol: 'S/', name: 'Sol péruvien' },
  { code: 'EGP', symbol: '£', name: 'Livre égyptienne' },
  { code: 'NGN', symbol: '₦', name: 'Naira nigérian' },
  { code: 'KES', symbol: 'KSh', name: 'Shilling kenyan' },
  { code: 'MAD', symbol: 'د.م.', name: 'Dirham marocain' },
  { code: 'TND', symbol: 'د.ت', name: 'Dinar tunisien' },
  { code: 'DZD', symbol: 'د.ج', name: 'Dinar algérien' },
  { code: 'XOF', symbol: 'CFA', name: 'Franc CFA (BCEAO)' },
  { code: 'XAF', symbol: 'FCFA', name: 'Franc CFA (BEAC)' },
  { code: 'GHS', symbol: 'GH₵', name: 'Cedi ghanéen' },
  { code: 'UGX', symbol: 'USh', name: 'Shilling ougandais' },
  { code: 'TZS', symbol: 'TSh', name: 'Shilling tanzanien' },
  { code: 'ETB', symbol: 'Br', name: 'Birr éthiopien' },
  { code: 'MUR', symbol: '₨', name: 'Roupie mauricienne' },
  { code: 'VND', symbol: '₫', name: 'Dong vietnamien' },
  { code: 'BDT', symbol: '৳', name: 'Taka bangladais' },
  { code: 'PKR', symbol: '₨', name: 'Roupie pakistanaise' },
  { code: 'LKR', symbol: '₨', name: 'Roupie srilankaise' },
  { code: 'UAH', symbol: '₴', name: 'Hryvnia ukrainienne' },
  { code: 'RON', symbol: 'lei', name: 'Leu roumain' },
  { code: 'BGN', symbol: 'лв', name: 'Lev bulgare' },
  { code: 'HRK', symbol: 'kn', name: 'Kuna croate' },
  { code: 'RSD', symbol: 'дин.', name: 'Dinar serbe' },
  { code: 'ISK', symbol: 'kr', name: 'Couronne islandaise' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Riyal qatarien' },
  { code: 'KWD', symbol: 'د.ك', name: 'Dinar koweïtien' },
  { code: 'BHD', symbol: 'د.ب', name: 'Dinar bahreïni' },
  { code: 'OMR', symbol: 'ر.ع.', name: 'Rial omanais' },
  { code: 'JOD', symbol: 'د.ا', name: 'Dinar jordanien' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Livre libanaise' },
  { code: 'IQD', symbol: 'ع.د', name: 'Dinar irakien' },
  { code: 'AFN', symbol: '؋', name: 'Afghani afghan' },
  { code: 'MMK', symbol: 'K', name: 'Kyat birman' },
  { code: 'KHR', symbol: '៛', name: 'Riel cambodgien' },
  { code: 'LAK', symbol: '₭', name: 'Kip laotien' },
  { code: 'NPR', symbol: '₨', name: 'Roupie népalaise' },
  { code: 'MVR', symbol: 'Rf', name: 'Rufiyaa maldivienne' },
  { code: 'BND', symbol: 'B$', name: 'Dollar de Brunei' },
  { code: 'FJD', symbol: 'FJ$', name: 'Dollar fidjien' },
  { code: 'PGK', symbol: 'K', name: 'Kina papouan' },
  { code: 'WST', symbol: 'WS$', name: 'Tala samoan' },
  { code: 'TOP', symbol: 'T$', name: 'Pa\'anga tongien' },
  { code: 'VUV', symbol: 'VT', name: 'Vatu vanuatuan' },
  { code: 'SBD', symbol: 'SI$', name: 'Dollar des Salomon' },
  { code: 'XPF', symbol: '₣', name: 'Franc Pacifique' },
  { code: 'AWG', symbol: 'ƒ', name: 'Florin arubais' },
  { code: 'BBD', symbol: 'Bds$', name: 'Dollar barbadien' },
  { code: 'BZD', symbol: 'BZ$', name: 'Dollar bélizien' },
  { code: 'BMD', symbol: 'BD$', name: 'Dollar bermudien' },
  { code: 'BSD', symbol: 'B$', name: 'Dollar bahaméen' },
  { code: 'JMD', symbol: 'J$', name: 'Dollar jamaïcain' },
  { code: 'TTD', symbol: 'TT$', name: 'Dollar de Trinité' },
  { code: 'XCD', symbol: 'EC$', name: 'Dollar des Caraïbes' },
  { code: 'HTG', symbol: 'G', name: 'Gourde haïtienne' },
  { code: 'DOP', symbol: 'RD$', name: 'Peso dominicain' },
  { code: 'GTQ', symbol: 'Q', name: 'Quetzal guatémaltèque' },
  { code: 'HNL', symbol: 'L', name: 'Lempira hondurien' },
  { code: 'NIO', symbol: 'C$', name: 'Córdoba nicaraguayen' },
  { code: 'CRC', symbol: '₡', name: 'Colón costaricain' },
  { code: 'PAB', symbol: 'B/.', name: 'Balboa panaméen' },
  { code: 'VES', symbol: 'Bs.S', name: 'Bolívar vénézuélien' },
  { code: 'GYD', symbol: 'G$', name: 'Dollar guyanien' },
  { code: 'SRD', symbol: 'Sr$', name: 'Dollar surinamais' },
  { code: 'UYU', symbol: '$U', name: 'Peso uruguayen' },
  { code: 'PYG', symbol: '₲', name: 'Guaraní paraguayen' },
  { code: 'BOB', symbol: 'Bs.', name: 'Boliviano bolivien' },
  { code: 'CUP', symbol: '₱', name: 'Peso cubain' },
  { code: 'CUC', symbol: 'CUC$', name: 'Peso cubain convertible' }
];

export const getCurrencyByCode = (code) => {
  return CURRENCIES.find(c => c.code === code) || CURRENCIES[0];
};

export const formatAmount = (amount, currencyCode) => {
  const currency = getCurrencyByCode(currencyCode);
  return `${amount.toFixed(2)} ${currency.symbol}`;
};
